services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.22.0
    entrypoint: ["mlflow", "server", "--host", "0.0.0.0", "--port", "8080"]
    ports:
      - "8080:8080"
    volumes:
      - mlflow_data:/mlflow/mlruns
    restart: unless-stopped

volumes:
  mlflow_data: